name: Check for updates in brew definitions
"on":
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Check for updates
      #   run: |
      #     LATEST=$(./check_latest_release)
      #     if [ -z "${LATEST}" ]; then
      #       echo "::set-env name=LATEST::${LATEST}"
      #     else
      #       exit 1
      #     fi

      # - name: test script
      #   run: |
      #     ./check_latest_release.sh

      - uses: technote-space/create-pr-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXECUTE_COMMANDS: bash ./check_latest_release.sh
          COMMIT_MESSAGE: 'Updated version automagically'
          COMMIT_NAME: 'Version bump'
          COMMIT_EMAIL: 'james@terminaloutcomes.com'
          PR_BRANCH_NAME: 'brew-update-${PR_ID}'
          PR_TITLE: 'Update to version'